const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  ADD_DISCOUNT: 'ADD_DISCOUNT',
  ADD_PROMO: 'ADD_PROMO',
  ADD_CART_TOTAL: 'ADD_CART_TOTAL',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  RESET_CART: 'RESET_CART'
};

export default CartActionTypes;